# REMEMBER TO EDIT .ENV & /ETC/HOSTS BEFORE USING THIS
version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '400:80'
    restart: always
    env_file: .env
    volumes: 
     - type: bind
       source: ./wpdata
       target: /var/www/html
    #   - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
      VIRTUAL_HOST: $WP_URL
    networks:
      - wpsite
      - proxy-tier

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: .env
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD 
    networks:
      - wpsite
      - proxy-tier

networks:
  wpsite:
  proxy-tier:
    external:
      name: nginx-proxy

volumes:
        #  wp_data:
  db_data: {}
